language: generic
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
        - os: linux
          dist: trusty
          sudo: required
          addons:
            apt:
              sources:    
                - ubuntu-toolchain-r-test
              packages:
                - g++-6
          env: 
            - CC=gcc-6 
            - CXX=g++-6 
            - ONLY_CPP=1
        - os: linux
          dist: trusty
          sudo: required
          addons:
            apt:
              sources:    
                - ubuntu-toolchain-r-test
              packages:
                - g++-7
          env: 
            - CC=gcc-7
            - CXX=g++-7
            - ONLY_CPP=1
        - os: linux
          dist: trusty
          sudo: required
        - os: linux
          dist: trusty
          sudo: required
        - os: osx
          osx_image: xcode7.2
        - os: osx
          osx_image: xcode8.3
        - os: osx
          osx_image: xcode9.1

before_install:
    ./scripts/before_install.sh

install:
    ./scripts/install.sh

before_script:
    ./scripts/before_script.sh

script:
    ./scripts/script.sh

notifications:
    email:
        recipients:
            - mike.h.bao@gmail.com
        on_success: always
        on_failure: always

git:
    depth: 3
